### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by samoht** [oklm-wsh/Decompress#1]
Can I use that library now or should I wait a little bit longer? :-)

**Comment by dinosaure** [comment]
Inflate is functional. I just finished to implementing a deflate algorithm, but I did not debug yet.

After that, I will release the first version in end of August and I will have something totally functional.

**Comment by samoht** [comment]
That's great, I'm looking forward to use the first version as an implementation of https://github.com/samoht/ocaml-git/blob/master/lib/inflate.mli#L19 Would make very easy to port `ocaml-git` on some weird platforms.

**Comment by dinosaure** [comment]
I just fix a lot of bug and I can deflate and inflate the content, there is no more than a bug (eg. Adler32 verification).

Then I will use the example on [ocaml-imap implementation](https://github.com/nojb/ocaml-imap/blob/master/lib/imap.ml#L1961) and I may changed the implementation to CPS style.

I think staying on schedule.

**Comment by samoht** [comment]
great, thanks for the update and continue the good work!

**Comment by dinosaure** [comment]
I think it is good starting point for this library now :+1: ! I will re-release this version in a few days and I'd wait for a feedback.
