### ISSUE TITLE
docker build?

### ISSUE THREAD

**Issue by justincormack** [oklm-wsh/Decompress#21]
It would be really nice if you could add a `Dockerfile` and automated build on Docker Hub so I could easily try this out without having to build it.

@avsm has a nice set of Ocaml base containers which make it easier.

**Comment by avsm** [comment]
see #22, no binaries seem to be installed though -- could we have a
decompress.install file that adds them to the opam bin path?

**Comment by dinosaure** [comment]
Close by #23.
